# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en
title: Arkeytek
title_separator: '-'
title_image: /assets/images/header/header.jpg
twitter_title_image: /assets/images/header/header.jpg
name: Aaron Ralls
email: arkeytekllc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
repository: "aaronralls/aaronralls.github.io"  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arkeytek.com" # the base hostname & protocol for your site, e.g. http://example.com
prod_url: "https://arkeytek.com"
twitter_username: cajunAA
github_username:  aaronralls
facebook_username: aaron.ralls.9
facebook_APPID: 579521919053592
linkedin_username: aaron-ralls
stackoverflow_username: aaronR
instagram_username: double_a_ralls
youtube_channel: UCOi8VW2MisYv8u1Qx7MFa5A
youtube_channel_name: aaron ralls
words_per_minute: 200
google_analytics: UA-58149846-3
facebook_pixel: 359995938150048
#include: ["_pages"] 

header_pages:
  - about.md
  - policy.md

show_excerpts: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Aaron Ralls
      author_profile: true
      share: true
      read_time: true
      related: true
      permalink: '/:year/:month/:day/:title'
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
  #auto_ids: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - assets_original
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#paginate: 3
#paginate_path: '/page:num/'

#gems:
#  - jekyll-paginate
#whitelist:
#  - jekyll-paginate

#Collections
collections:
  authors:
    output: true
